production:
  sessions:
    default:
      database: nation_builder_production
      hosts:
        - localhost:27017
      options:
  options:
    raise_not_found_error: false

development:
  sessions:
    default:
      database: nation_builder_development
      hosts:
        - localhost:27017
      options:
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      database: nation_builder_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
  options:
    raise_not_found_error: false